# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groupDB.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='groupDB.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgroupDB.proto\"4\n\x0f\x61\x64\x64GroupRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tgroupName\x18\x02 \x01(\t\"7\n\x12\x64\x65leteGroupRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tgroupName\x18\x02 \x01(\t\" \n\raddGroupReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x10\x64\x65leteGroupReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n\x0fgetGroupRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tgroupName\x18\x02 \x01(\t\" \n\rgetGroupReply\x12\x0f\n\x07groupId\x18\x01 \x01(\x05\"\'\n\x10removeAllRequest\x12\x13\n\x0bplaceHolder\x18\x01 \x01(\x08\"!\n\x0eremoveAllReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd8\x01\n\x08\x64\x61tabase\x12.\n\x08\x61\x64\x64Group\x12\x10.addGroupRequest\x1a\x0e.addGroupReply\"\x00\x12\x37\n\x0b\x64\x65leteGroup\x12\x13.deleteGroupRequest\x1a\x11.deleteGroupReply\"\x00\x12\x30\n\ngetGroupId\x12\x10.getGroupRequest\x1a\x0e.getGroupReply\"\x00\x12\x31\n\tremoveAll\x12\x11.removeAllRequest\x1a\x0f.removeAllReply\"\x00\x62\x06proto3')
)




_ADDGROUPREQUEST = _descriptor.Descriptor(
  name='addGroupRequest',
  full_name='addGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='addGroupRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupName', full_name='addGroupRequest.groupName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=69,
)


_DELETEGROUPREQUEST = _descriptor.Descriptor(
  name='deleteGroupRequest',
  full_name='deleteGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='deleteGroupRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupName', full_name='deleteGroupRequest.groupName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=126,
)


_ADDGROUPREPLY = _descriptor.Descriptor(
  name='addGroupReply',
  full_name='addGroupReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='addGroupReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=160,
)


_DELETEGROUPREPLY = _descriptor.Descriptor(
  name='deleteGroupReply',
  full_name='deleteGroupReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='deleteGroupReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=197,
)


_GETGROUPREQUEST = _descriptor.Descriptor(
  name='getGroupRequest',
  full_name='getGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='getGroupRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupName', full_name='getGroupRequest.groupName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=251,
)


_GETGROUPREPLY = _descriptor.Descriptor(
  name='getGroupReply',
  full_name='getGroupReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='getGroupReply.groupId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=285,
)


_REMOVEALLREQUEST = _descriptor.Descriptor(
  name='removeAllRequest',
  full_name='removeAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='placeHolder', full_name='removeAllRequest.placeHolder', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=326,
)


_REMOVEALLREPLY = _descriptor.Descriptor(
  name='removeAllReply',
  full_name='removeAllReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='removeAllReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=361,
)

DESCRIPTOR.message_types_by_name['addGroupRequest'] = _ADDGROUPREQUEST
DESCRIPTOR.message_types_by_name['deleteGroupRequest'] = _DELETEGROUPREQUEST
DESCRIPTOR.message_types_by_name['addGroupReply'] = _ADDGROUPREPLY
DESCRIPTOR.message_types_by_name['deleteGroupReply'] = _DELETEGROUPREPLY
DESCRIPTOR.message_types_by_name['getGroupRequest'] = _GETGROUPREQUEST
DESCRIPTOR.message_types_by_name['getGroupReply'] = _GETGROUPREPLY
DESCRIPTOR.message_types_by_name['removeAllRequest'] = _REMOVEALLREQUEST
DESCRIPTOR.message_types_by_name['removeAllReply'] = _REMOVEALLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addGroupRequest = _reflection.GeneratedProtocolMessageType('addGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPREQUEST,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:addGroupRequest)
  })
_sym_db.RegisterMessage(addGroupRequest)

deleteGroupRequest = _reflection.GeneratedProtocolMessageType('deleteGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGROUPREQUEST,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:deleteGroupRequest)
  })
_sym_db.RegisterMessage(deleteGroupRequest)

addGroupReply = _reflection.GeneratedProtocolMessageType('addGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPREPLY,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:addGroupReply)
  })
_sym_db.RegisterMessage(addGroupReply)

deleteGroupReply = _reflection.GeneratedProtocolMessageType('deleteGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGROUPREPLY,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:deleteGroupReply)
  })
_sym_db.RegisterMessage(deleteGroupReply)

getGroupRequest = _reflection.GeneratedProtocolMessageType('getGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGROUPREQUEST,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:getGroupRequest)
  })
_sym_db.RegisterMessage(getGroupRequest)

getGroupReply = _reflection.GeneratedProtocolMessageType('getGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _GETGROUPREPLY,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:getGroupReply)
  })
_sym_db.RegisterMessage(getGroupReply)

removeAllRequest = _reflection.GeneratedProtocolMessageType('removeAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEALLREQUEST,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:removeAllRequest)
  })
_sym_db.RegisterMessage(removeAllRequest)

removeAllReply = _reflection.GeneratedProtocolMessageType('removeAllReply', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEALLREPLY,
  '__module__' : 'groupDB_pb2'
  # @@protoc_insertion_point(class_scope:removeAllReply)
  })
_sym_db.RegisterMessage(removeAllReply)



_DATABASE = _descriptor.ServiceDescriptor(
  name='database',
  full_name='database',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=364,
  serialized_end=580,
  methods=[
  _descriptor.MethodDescriptor(
    name='addGroup',
    full_name='database.addGroup',
    index=0,
    containing_service=None,
    input_type=_ADDGROUPREQUEST,
    output_type=_ADDGROUPREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteGroup',
    full_name='database.deleteGroup',
    index=1,
    containing_service=None,
    input_type=_DELETEGROUPREQUEST,
    output_type=_DELETEGROUPREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getGroupId',
    full_name='database.getGroupId',
    index=2,
    containing_service=None,
    input_type=_GETGROUPREQUEST,
    output_type=_GETGROUPREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removeAll',
    full_name='database.removeAll',
    index=3,
    containing_service=None,
    input_type=_REMOVEALLREQUEST,
    output_type=_REMOVEALLREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASE)

DESCRIPTOR.services_by_name['database'] = _DATABASE

# @@protoc_insertion_point(module_scope)
