# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-06 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_ID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
