# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_auto_20191205_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_ID',
            field=models.IntegerField(default=0),
        ),
    ]
