# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-15 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0004_auto_20191214_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
