# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='groups.proto',
  package='groups_members',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cgroups.proto\x12\x0egroups_members\"5\n\x10\x41\x64\x64MemberRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\" \n\x0e\x41\x64\x64MemberReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"8\n\x13RemoveMemberRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"#\n\x11RemoveMemberReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"4\n\x0f\x43ontainsRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x1f\n\rContainsReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"%\n\x11\x41llMembersRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\"!\n\x0f\x41llMembersReply\x12\x0e\n\x06result\x18\x01 \x03(\t\"&\n\x12\x44\x65leteGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\"\"\n\x10\x44\x65leteGroupReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xb4\x03\n\x0eGroups_Manager\x12O\n\tAddMember\x12 .groups_members.AddMemberRequest\x1a\x1e.groups_members.AddMemberReply\"\x00\x12X\n\x0cRemoveMember\x12#.groups_members.RemoveMemberRequest\x1a!.groups_members.RemoveMemberReply\"\x00\x12L\n\x08\x43ontains\x12\x1f.groups_members.ContainsRequest\x1a\x1d.groups_members.ContainsReply\"\x00\x12R\n\nAllMembers\x12!.groups_members.AllMembersRequest\x1a\x1f.groups_members.AllMembersReply\"\x00\x12U\n\x0b\x44\x65leteGroup\x12\".groups_members.DeleteGroupRequest\x1a .groups_members.DeleteGroupReply\"\x00\x62\x06proto3')
)




_ADDMEMBERREQUEST = _descriptor.Descriptor(
  name='AddMemberRequest',
  full_name='groups_members.AddMemberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='groups_members.AddMemberRequest.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='groups_members.AddMemberRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=85,
)


_ADDMEMBERREPLY = _descriptor.Descriptor(
  name='AddMemberReply',
  full_name='groups_members.AddMemberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='groups_members.AddMemberReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=119,
)


_REMOVEMEMBERREQUEST = _descriptor.Descriptor(
  name='RemoveMemberRequest',
  full_name='groups_members.RemoveMemberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='groups_members.RemoveMemberRequest.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='groups_members.RemoveMemberRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=177,
)


_REMOVEMEMBERREPLY = _descriptor.Descriptor(
  name='RemoveMemberReply',
  full_name='groups_members.RemoveMemberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='groups_members.RemoveMemberReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=214,
)


_CONTAINSREQUEST = _descriptor.Descriptor(
  name='ContainsRequest',
  full_name='groups_members.ContainsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='groups_members.ContainsRequest.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='groups_members.ContainsRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=268,
)


_CONTAINSREPLY = _descriptor.Descriptor(
  name='ContainsReply',
  full_name='groups_members.ContainsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='groups_members.ContainsReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=301,
)


_ALLMEMBERSREQUEST = _descriptor.Descriptor(
  name='AllMembersRequest',
  full_name='groups_members.AllMembersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='groups_members.AllMembersRequest.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=340,
)


_ALLMEMBERSREPLY = _descriptor.Descriptor(
  name='AllMembersReply',
  full_name='groups_members.AllMembersReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='groups_members.AllMembersReply.result', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=375,
)


_DELETEGROUPREQUEST = _descriptor.Descriptor(
  name='DeleteGroupRequest',
  full_name='groups_members.DeleteGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='groups_members.DeleteGroupRequest.group_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=415,
)


_DELETEGROUPREPLY = _descriptor.Descriptor(
  name='DeleteGroupReply',
  full_name='groups_members.DeleteGroupReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='groups_members.DeleteGroupReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=451,
)

DESCRIPTOR.message_types_by_name['AddMemberRequest'] = _ADDMEMBERREQUEST
DESCRIPTOR.message_types_by_name['AddMemberReply'] = _ADDMEMBERREPLY
DESCRIPTOR.message_types_by_name['RemoveMemberRequest'] = _REMOVEMEMBERREQUEST
DESCRIPTOR.message_types_by_name['RemoveMemberReply'] = _REMOVEMEMBERREPLY
DESCRIPTOR.message_types_by_name['ContainsRequest'] = _CONTAINSREQUEST
DESCRIPTOR.message_types_by_name['ContainsReply'] = _CONTAINSREPLY
DESCRIPTOR.message_types_by_name['AllMembersRequest'] = _ALLMEMBERSREQUEST
DESCRIPTOR.message_types_by_name['AllMembersReply'] = _ALLMEMBERSREPLY
DESCRIPTOR.message_types_by_name['DeleteGroupRequest'] = _DELETEGROUPREQUEST
DESCRIPTOR.message_types_by_name['DeleteGroupReply'] = _DELETEGROUPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddMemberRequest = _reflection.GeneratedProtocolMessageType('AddMemberRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMEMBERREQUEST,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.AddMemberRequest)
  })
_sym_db.RegisterMessage(AddMemberRequest)

AddMemberReply = _reflection.GeneratedProtocolMessageType('AddMemberReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDMEMBERREPLY,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.AddMemberReply)
  })
_sym_db.RegisterMessage(AddMemberReply)

RemoveMemberRequest = _reflection.GeneratedProtocolMessageType('RemoveMemberRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEMEMBERREQUEST,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.RemoveMemberRequest)
  })
_sym_db.RegisterMessage(RemoveMemberRequest)

RemoveMemberReply = _reflection.GeneratedProtocolMessageType('RemoveMemberReply', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEMEMBERREPLY,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.RemoveMemberReply)
  })
_sym_db.RegisterMessage(RemoveMemberReply)

ContainsRequest = _reflection.GeneratedProtocolMessageType('ContainsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINSREQUEST,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.ContainsRequest)
  })
_sym_db.RegisterMessage(ContainsRequest)

ContainsReply = _reflection.GeneratedProtocolMessageType('ContainsReply', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINSREPLY,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.ContainsReply)
  })
_sym_db.RegisterMessage(ContainsReply)

AllMembersRequest = _reflection.GeneratedProtocolMessageType('AllMembersRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLMEMBERSREQUEST,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.AllMembersRequest)
  })
_sym_db.RegisterMessage(AllMembersRequest)

AllMembersReply = _reflection.GeneratedProtocolMessageType('AllMembersReply', (_message.Message,), {
  'DESCRIPTOR' : _ALLMEMBERSREPLY,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.AllMembersReply)
  })
_sym_db.RegisterMessage(AllMembersReply)

DeleteGroupRequest = _reflection.GeneratedProtocolMessageType('DeleteGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGROUPREQUEST,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.DeleteGroupRequest)
  })
_sym_db.RegisterMessage(DeleteGroupRequest)

DeleteGroupReply = _reflection.GeneratedProtocolMessageType('DeleteGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGROUPREPLY,
  '__module__' : 'groups_pb2'
  # @@protoc_insertion_point(class_scope:groups_members.DeleteGroupReply)
  })
_sym_db.RegisterMessage(DeleteGroupReply)



_GROUPS_MANAGER = _descriptor.ServiceDescriptor(
  name='Groups_Manager',
  full_name='groups_members.Groups_Manager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=454,
  serialized_end=890,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddMember',
    full_name='groups_members.Groups_Manager.AddMember',
    index=0,
    containing_service=None,
    input_type=_ADDMEMBERREQUEST,
    output_type=_ADDMEMBERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveMember',
    full_name='groups_members.Groups_Manager.RemoveMember',
    index=1,
    containing_service=None,
    input_type=_REMOVEMEMBERREQUEST,
    output_type=_REMOVEMEMBERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Contains',
    full_name='groups_members.Groups_Manager.Contains',
    index=2,
    containing_service=None,
    input_type=_CONTAINSREQUEST,
    output_type=_CONTAINSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AllMembers',
    full_name='groups_members.Groups_Manager.AllMembers',
    index=3,
    containing_service=None,
    input_type=_ALLMEMBERSREQUEST,
    output_type=_ALLMEMBERSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteGroup',
    full_name='groups_members.Groups_Manager.DeleteGroup',
    index=4,
    containing_service=None,
    input_type=_DELETEGROUPREQUEST,
    output_type=_DELETEGROUPREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GROUPS_MANAGER)

DESCRIPTOR.services_by_name['Groups_Manager'] = _GROUPS_MANAGER

# @@protoc_insertion_point(module_scope)
